;;; base16-dotfiles-colors.el --- load the active base16 palette -*- lexical-binding: t; -*-
;;; Commentary:
;; Split out of base16-dotfiles-theme.el (ADR-0009) so `config.el` can load
;; this directly and have `base16-dotfiles-theme-colors' bound immediately —
;; Doom doesn't call `load-theme' (which is what would otherwise load this)
;; until `window-setup-hook', well after config.el's `custom-set-faces!'
;; block has already evaluated its `zf/base16-color' calls.
;;
;; Colors are NOT hardcoded here: `theme-colors.el`, sitting next to this
;; file, is generated by `scripts/theme-switch <family>` and sets
;; `base16-dotfiles-theme-colors'. The onedark fallback below only covers the
;; window between a fresh clone/rebuild and the first theme-switch run.
;;; Code:
(defvar base16-dotfiles-theme-colors
  '(:base00 "#282c34" :base01 "#353b45" :base02 "#3e4451" :base03 "#545862"
    :base04 "#565c64" :base05 "#abb2bf" :base06 "#b6bdca" :base07 "#c8ccd4"
    :base08 "#e06c75" :base09 "#d19a66" :base0A "#e5c07b" :base0B "#98c379"
    :base0C "#56b6c2" :base0D "#61afef" :base0E "#c678dd" :base0F "#be5046")
  "Active base16 palette. Overwritten by the generated theme-colors.el.")

(load (expand-file-name "theme-colors.el" (file-name-directory
                                            (or load-file-name buffer-file-name)))
      'noerror 'nomessage)

(provide 'base16-dotfiles-colors)
;;; base16-dotfiles-colors.el ends here
