#!/bin/sh

# --------------------- #
# Weekly Review Process #
# --------------------- #


# setup
CURRENT="${HOME}/wiki/review/current.md"

NOW=$( date +%Y.%W )
NOWFILE="${HOME}/wiki/review/${NOW}.md"

PAST=$( date -v-1w  +%Y.%W )
PASTFILE="${HOME}/wiki/review/${PAST}.md"

NEXT=$( date -v+1w  +%Y.%W )


# check for current review file at path above
if ! [ -f $CURRENT ]; then
    echo "Sorry, can't find your current review."
    exit 1
fi

# check for previous review file at path above
if [ -f $PASTFILE ]; then
    # last week's review has been completed so we need to end the current
    # review at ${NOW} and start the new review at ${NEXT}
    echo "Last week's review was already completed. See " + ${PASTFILE}
    echo
    read -rp "Would you like to end the current review now and create next week's review? y/n  " answer
    case ${answer:0:1} in
        y|Y )
            END=${NOW}
            ENDFILE=${NOWFILE}

            START=${NEXT}
            ;;
        * )
            exit 1
            ;;
    esac
else
    # last week's review is not yet completed, so let's do it now. end current
    # review at ${PAST} and start new review at ${NOW}
    END=${PAST}
    ENDFILE=${PASTFILE}

    START=${NOW}
fi


# grab previous review from current file
echo "Completing Review for ${END}..."
# paste it into it's own archive
sed -n '/^-----/,$ {//!p;}' ${CURRENT} | sed '1d' > ${ENDFILE}
# will edit/append later


# replace previous review with blank review template
echo "Starting Review for ${START}..."
# TODO: hook up a quote API to replace the quote every week
cat << EOF > ${CURRENT}
# Current Review

The best laid plans of mice and men often go awry.

*Plan Anyway!*

-----

# ${START}


## Goals:

- [ ]


## Time:

- Work:
- People:
- Elective - Productive:
- Elective - Play:
- Health:
- Sleep:


## Review:

EOF

# time to edit/append both files accordingly
vim ${ENDFILE} ${CURRENT}

# exit
echo
echo "Good work. A planned week makes a prepared person."

