# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/fbfa0f6a-150a-4697-a6d7-290086333b64";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D766-3788";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/games" =
    { device = "/dev/disk/by-uuid/A856EE5E56EE2D2E";
      fsType = "ntfs";
      options = [ "users" "nofail" "uid=1000" "gid=100" ];
    };

  fileSystems."/mnt/media" =
    { device = "/dev/disk/by-uuid/3E26D72926D6E147";
      fsType = "ntfs";
      options = [ "users" "nofail" "uid=1000" "gid=100" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/b93459ed-5165-4359-a7a4-e6c825ee6f56"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
